tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "act"
brew "coreutils"
brew "asdf"
brew "bash"
brew "bash-completion"
brew "bat"
brew "black"
brew "borgbackup"
brew "colordiff"
brew "curl"
brew "dict"
brew "gh"
brew "git"
brew "git-delta"
brew "pinentry"
brew "gnupg"
brew "go"
brew "golangci-lint"
brew "grc"
brew "grep"
brew "htmltest"
brew "htop"
brew "hugo"
brew "ipython"
brew "ispell"
brew "jq"
brew "mackup"
brew "mas"
brew "mosh"
brew "mtr"
brew "node"
brew "openjdk"
brew "openssh"
brew "p7zip"
brew "pipenv"
brew "podman"
brew "poetry"
brew "pv"
brew "ruby-build"
brew "rbenv"
brew "rbenv-bundle-exec"
brew "rbenv-bundler"
brew "rust"
brew "speedtest-cli"
brew "starship"
brew "subversion"
brew "tmux"
brew "vale"
brew "virtualenv"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
cask "alt-tab"
cask "balance-lock"
cask "brave-browser"
cask "coconutbattery"
cask "dupeguru"
cask "emacs"
cask "font-hasklig"
cask "font-inter"
cask "font-jetbrains-mono"
cask "font-roboto-mono-for-powerline"
cask "font-source-code-pro"
cask "garmin-basecamp"
cask "garmin-express"
cask "goldencheetah"
cask "handbrake"
cask "iglance"
cask "iterm2"
cask "keepassxc"
cask "logitech-camera-settings"
cask "signal"
cask "superduper"
cask "switchresx"
cask "visual-studio-code"
cask "vlc"
cask "xscreensaver"
cask "yubico-authenticator"
cask "yubico-yubikey-manager"
cask "yubico-yubikey-personalization-gui"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Evernote Web Clipper", id: 1481669779
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Toothpicks", id: 998361254
mas "Wipr", id: 1320666476
mas "Xcode", id: 497799835
