tap "homebrew/bundle"
tap "homebrew/services"
brew "ca-certificates"
brew "asdf"
brew "bash"
brew "bash-completion"
brew "bat"
brew "black"
brew "borgbackup"
brew "colordiff"
brew "coreutils"
brew "curl"
brew "dict"
brew "gh"
brew "git"
brew "git-delta"
brew "pinentry"
brew "gnupg"
brew "go"
brew "golangci-lint"
brew "grep"
brew "htmltest"
brew "htop"
brew "hugo"
brew "ipython"
brew "ispell"
brew "jq"
brew "libdvbpsi"
brew "libdvdcss"
brew "libdvdnav"
brew "mackup"
brew "mas"
brew "mosh"
brew "mtr"
brew "node"
brew "openjdk"
brew "openssh"
brew "p7zip"
brew "pkgconf"
brew "podman"
brew "poetry"
brew "pv"
brew "ruby-build"
brew "rbenv"
brew "rbenv-bundle-exec"
brew "rbenv-bundler"
brew "rust"
brew "speedtest-cli"
brew "starship"
brew "subversion"
brew "telnet"
brew "tmux"
brew "vale"
brew "virtualenv"
brew "w3m"
brew "watch"
brew "wget"
brew "wimlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
cask "balance-lock"
cask "brave-browser"
cask "chirp"
cask "coconutbattery"
cask "crystalfetch"
cask "dupeguru"
cask "emacs"
cask "fldigi"
cask "flrig"
cask "font-hasklig"
cask "font-inter"
cask "font-jetbrains-mono"
cask "font-roboto-mono-for-powerline"
cask "font-source-code-pro"
cask "fujitsu-scansnap-home"
cask "garmin-express"
cask "goldencheetah"
cask "gridtracker2"
cask "handbrake"
cask "iglance"
cask "iterm2"
cask "keepassxc"
cask "remotehamradio"
cask "send-to-kindle"
cask "signal"
cask "superduper"
cask "tqsl"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "yubico-authenticator"
cask "yubico-yubikey-manager"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Copilot", id: 1447330651
mas "Day Progress", id: 6450280202
mas "GarageBand", id: 682658836
mas "HAM-Toolbox", id: 1630108109
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "lire", id: 1482527526
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 639968404
mas "Pixelmator Pro", id: 1289583905
mas "Prime Video", id: 545519333
mas "PulseQSO", id: 1629134275
mas "RadarScope", id: 288419283
mas "RUMlogNG", id: 964454561
mas "StopTheFonts", id: 1671452642
mas "StopTheMadness Pro", id: 6471380298
mas "Tailscale", id: 1475387142
mas "Things", id: 904280696
mas "Toothpicks", id: 998361254
mas "Wipr", id: 1662217862
vscode "bierner.markdown-mermaid"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "christian-kohler.npm-intellisense"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.code-runner"
vscode "github.codespaces"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "gitlab.gitlab-workflow"
vscode "golang.go"
vscode "google.geminicodeassist"
vscode "googlecloudtools.cloudcode"
vscode "hoovercj.vscode-power-mode"
vscode "lextudio.restructuredtext"
vscode "lfs.vscode-emacs-friendly"
vscode "mattn.lisp"
vscode "miguelsolorio.fluent-icons"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.live-server"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vsliveshare.vsliveshare"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "sleistner.vscode-fileutils"
vscode "stkb.rewrap"
vscode "streetsidesoftware.code-spell-checker"
vscode "takumii.markdowntable"
vscode "tamj0rd2.ts-quickfixes-extension"
vscode "tomoki1207.pdf"
vscode "tomoyukim.vscode-mermaid-editor"
vscode "travisthetechie.write-good-linter"
vscode "usernamehw.errorlens"
vscode "vscode-org-mode.org-mode"
vscode "vstirbu.vscode-mermaid-preview"
vscode "xabikos.javascriptsnippets"
