#!/bin/bash
set -eu

cd "$(dirname $0)"

bold=$(tput bold)
green=$(tput setaf 2)
normal=$(tput sgr0)

title() {
  echo "${bold}==> $1${normal}"
  echo
}

indent() {
  sed 's/^/  /'
}

echo

# If macOS
if [[ "$(uname)" == "Darwin" ]]; then
  echo "Setting path"
  export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

  # Install brew
  if test ! $(which brew); then
    title "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo
  fi

  # Disable Brew analytics
  brew analytics off

  # Install brew packages
  title "Installing software..."
  brew bundle | indent
  echo
  brew doctor

  # Fix permissions for Zsh compaudit
  chmod g-w /opt/homebrew/share

  # Link Brew OpenJDK
  sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

  # Ensure zsh is a valid shell option
  if ! cat /etc/shells | grep /opt/homebrew/bin/zsh > /dev/null; then
    title "Adding zsh to list of allowed shells..."
    sudo sh -c 'echo /opt/homebrew/bin/zsh >> /etc/shells'
    echo
  fi

  # Use Touch ID for sudo
  if ! cat /etc/pam.d/sudo | grep pam_tid > /dev/null; then
    sudo sed -i '' '2i\
auth       sufficient     pam_tid.so
' /etc/pam.d/sudo
  fi

  title "Configuring macOS..."
  ./scripts/configure-macos
  echo "Defaults configured!" | indent
  echo

fi

# Install symlinks
title "Configuring software..."
./scripts/install-symlinks

# Install yarn packages
# if test $(which yarn); then
#   title "Installing yarn packages..."
#   (cd "$HOME"/.config/yarn/global && yarn install 2>&1) | indent
#   echo
# fi

# Check that we are using zsh
if [[ "$SHELL" != *"zsh"* ]]; then
  if [[ "$(uname)" == "Darwin" ]]; then
    title "Changing user shell to zsh..."
    chsh -s /opt/homebrew/bin/zsh
    echo "Your shell has been changed to zsh, please restart your terminal or tab" | indent
    echo
  else
    echo "You are not using zsh, after installing, please run 'chsh -s /path/to/zsh'" | indent
    echo
  fi
fi

echo "${green}All done!${normal}" | indent
